image: node:latest

.deployment:
  only:
    - /^release\/.*$/

stages:
  - deploy

deployCompleteSet:
  extends: .deployment
  stage: deploy
  script:
    - npm install -g npm-cli-login
    - npm-cli-login -u $NPM_USER -p $NPM_USER_PW -e $NPM_USER_EMAIL
    - version=$(echo ${CI_COMMIT_REF_NAME} | sed 's/.*v//' | sed 's/$/.0/g')
    - cd ./rulesets/restCompleteSet/
    - npm version $version
    - npm publish --access public