image: node:latest

.deployment:
  only:
    - /^release\/.*$/

stages:
  - deploy

deployCompleteSet:
  extends: .deployment
  stage: deploy
  script:
    - npm config set @doubleslashde:registry https://registry.npmjs.org/
    - echo "//registry.npmjs.org/:_authToken:${NPM_TOKEN}" >> .npmrc
    - version=$(echo ${CI_COMMIT_REF_NAME} | sed 's/.*v//' | sed 's/$/.0/g')
    - cd ./rulesets/restCompleteSet/
    - npm version $version
    - npm publish